### ISSUE TITLE
fountain.lua:4: module 'inspect' not found

### ISSUE THREAD

**Issue by andrashann** [pandoc/pandoc-fountain#1]
I'm trying to use this reader on MacOS; for the sake of simplicity, I downloaded the code in the repo and unzipped everything in the same folder as my .fountain file is.

`pandoc -f fountain.lua --reference-doc fountain-ref.docx myfile.fountain -o myfile.docx` throws the following error:

```
Error running Lua:
fountain.lua:4: module 'inspect' not found:
	inspect is not one of pandoc's default packages
	no field package.preload['inspect']
	no file '/usr/local/share/lua/5.3/inspect.lua'
	no file '/usr/local/share/lua/5.3/inspect/init.lua'
	no file '/usr/local/lib/lua/5.3/inspect.lua'
	no file '/usr/local/lib/lua/5.3/inspect/init.lua'
	no file './inspect.lua'
	no file './inspect/init.lua'
	no file '/usr/local/lib/lua/5.3/inspect.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './inspect.so'
stack traceback:
	[C]: in function 'require'
	fountain.lua:4: in main chunk
```
	
I installed pandoc via homebrew. I tried installing inspect using `luarocks install inspect`, and it is installed, but in a different location:

```
>> luarocks list                                                                                       

Rocks installed for Lua 5.4
---------------------------

inspect
   3.1.3-0 (installed) - /opt/homebrew/lib/luarocks/rocks-5.4
```

I am not sure how to proceed from here.

**Comment by jgm** [comment]
I fixed this.  Alternatively you could just `luarocks install inspect` (ah, I see you tried this but were using Lua 5.4; pandoc uses 5.3), but the `inspect` module was only needed for debugging, so I removed it.
